version: "3.1"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    command: mongod --auth
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Pas@123
      MONGO_INITDB_DATABASE: spring-webflux-restful
    volumes:
      - ./mongodb:/data/db
      - ./mongodb:/var/log/mongodb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - spring-webflux

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Pas@123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - spring-webflux

  spring-app:
    container_name: spring-app
    image: sukendakenda/spring-webflux-restful
    ports:
      - 9090:8080
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      LOGGING_LEVEL_WEB: TRACE
    networks:
      - spring-webflux
    depends_on:
      - mongodb

networks:
  spring-webflux:
    name: spring-webflux
    driver: bridge